Shoppy/Shoppy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('products.urls', namespace='products')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shoppy/products/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^logout$', auth_views.logout, {'next_page':'/'}, name='logout'),
    url(r'^login/$', views.auth_login, name='autentication'),
    url(r'^$', views.ProductListView.as_view(), name='hola'),
    #url(r'^product/(?P<pk>[0-9]+)/$', views.product_detail, name='product_detail'),
    url(r'^product/(?P<pk>[0-9]+)/$', views.ProductDetail.as_view(), name='product_detail'),
    url(r'^product/new', views.new_product, name='new_product')
]

Shoppy/clients/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Client(models.Model):
    name = models.CharField(max_length=255)
    phone = models.IntegerField(unique=True)
    email = models.EmailField(max_length=255)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ('id',)

Shoppy/products/models.py
from __future__ import unicode_literals

from django.db import models
from clients.models import Client

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ('name',)

class Favorite(models.Model):
    user = models.ForeignKey(Client)
    product = models.ForeignKey(Product)

    class Meta:
        verbose_name = 'Favorite'
        verbose_name_plural = 'Favorites'

    def __str__(self):
        return '%s %s' % (self.user.name, self.product.name)

Shoppy/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

Shoppy/clients/views.py
from django.shortcuts import render

# Create your views here.

Shoppy/products/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.views.generic import ListView
from django.views.generic.detail import DetailView

from .forms import ProductForm
from .models import Product

# Create your views here.

'''def hello_world(request):
    #return HttpResponse('hola!')
    #return render(request, 'index.html')
    products = Product.objects.order_by('id')
    template = loader.get_template('index.html')
    context = {
        'products':products
    }
    return HttpResponse(template.render(context, request))'''
class ProductListView(ListView):
    model = Product

'''def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    template = loader.get_template('product_detail.html')
    context = {
        'product': product
    }
    return HttpResponse(template.render(context, request))'''
class ProductDetail(DetailView):
    model = Product

@login_required
def new_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            product.save()
            return HttpResponseRedirect('/')
    else:
        form = ProductForm()
    template = loader.get_template('new_product.html')
    context = {
        'form':form
    }
    return HttpResponse(template.render(context, request))

def auth_login(request):
    if request.method == 'POST':
        action = request.POST.get('action',None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        if action == 'singup':
            user = User.objects.create_user(username=username, password=password)
            user.save()
        elif action == 'login':
            user = authenticate(username=username, password=password)
            login(request,user)
            return redirect('/')
    context = {}
    return render(request, 'login/login.html', context)

Shoppy/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {%load staticfiles %}
    <meta charset="utf-8">
    <title>{% block page_title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    <header>
        hola
    </header>
    <section>
        {% block content %}
        {% endblock %}
    </section>
    <footer>
        el footer
    </footer>
  </body>
</html>

Shoppy/templates/index.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>hello_world</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <h1 style="color:red">hola</h1>
    <a href="{% url 'new_product' %}">New Product</a>
    <ul>
        {% for pr in products %}
            <li>
              <a href="{% url 'product_detail' pk=pr.pk %}">{{ pr.name }} </a>
              |
              {{ pr.description }}
              <img src="{{ pr.image.url }}" alt="">
            </li>
        {% endfor %}
    </ul>
</body>
</html>

Shoppy/templates/login/login.html
{% extends "base.html" %}

{% block page_title %}
    Login
{% endblock %}

{% block content %}
    <h1>Login</h1>
    <form class="" action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="login">
        <input type="text" name="username" value="">
        <input type="text" name="password" value="">
        <button type="submit" name="button">login</button>
    </form>
    <h1>Singup</h1>
    <form class="" action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="singup">
        <input type="text" name="username" value="">
        <input type="text" name="password" value="">
        <button type="submit" name="button">singup</button>
    </form>
{% endblock %}

Shoppy/templates/new_product.html
{% extends "base.html" %}

{% block page_title %}
    New article
{% endblock %}

{% block content %}
    <h1>New article</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="button">Submit</button>
    </form>
{% endblock %}

Shoppy/templates/product_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <h1>{{ product.name }}</h1>
    <h2>{{ product.description }}</h2>
    <p>{{ product.category }} |
       {{ product.price }}
    </p>
    <img src="{{ product.image.url }}" alt="">
{% endblock %}

Shoppy/templates/products/product_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <h1>{{ product.name }}</h1>
    <h2>{{ product.description }}</h2>
    <p>{{ product.category }} |
       {{ product.price }}
    </p>
    <img src="{{ product.image.url }}" alt="">
{% endblock %}

Shoppy/templates/products/product_list.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>hello_world</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <h1 style="color:red">hola
        {% if user.is_authenticated %}
            <h3>{{ user.username }} | <a href="{% url "products:logout" %}">Logout</a></h3>
        {% else %}
            <a href="{% url "products:autentication" %}">Login</a>
        {% endif %}
    </h1>
    <a href="{% url "products:new_product" %}">New Product</a>
    <ul>
        {% for pr in object_list %}
            <li>
              <a href="{% url "products:product_detail" pr.id %}">{{ pr.name }} </a>
              |
              {{ pr.description }}
              <img src="{{ pr.image.url }}" alt="">
            </li>
        {% endfor %}
    </ul>
</body>
</html>