login/loginDjango/loginDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('userprofiles.urls', namespace='userprofiles')),
    url(r'^admin/', admin.site.urls),
]

login/loginDjango/userprofiles/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', views.authentication, name='authentication'),
    url(r'^$', views.hello, name='hello'),
    url(r'^logout$', auth_views.logout, {'next_page':'/'}, name='logout')
]

login/loginDjango/userprofiles/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

login/loginDjango/userprofiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
# Create your views here.

def authentication(request):
    if request.method == 'POST':
        action = request.POST.get('action', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        if action == 'singup':
            user = User.objects.create_user(username=username,password=password)
            user.save()
        elif action == 'login':
            user = authenticate(username=username, password=password)
            login(request, user)
        return redirect('/')

    return render(request, 'login.html', {})

def hello(request):
    return render(request, 'hello.html', {})

login/loginDjango/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login Django</title>
  </head>
  <body>
      {% block login_content %}
      {% endblock %}
      {% block content %}
      {% endblock %}
  </body>
</html>

login/loginDjango/templates/hello.html
{% extends "base.html" %}

{% block content %}
 <h1>Hola!!</h1>


 <h2>
    {% if user.is_authenticated %}
        <a href="{% url 'userprofiles:logout' %}">logout</a>
        {{ user.username }}
    {% else %}
        <a href="{% url 'userprofiles:authentication' %}">Login</a>
    {% endif %}
 </h2>
{% endblock %}

login/loginDjango/templates/login.html
{% extends "base.html" %}

{% block login_content %}
    <h1>Login</h1>
    <form class="" action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="login">
        <input type="text" name="username" value="">
        <input type="text" name="password" value="">
        <button type="submit" name="button">Login</button>

    </form>
    <h1>Singup</h1>
    <form class="" action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="singup">
        <input type="text" name="username" value="">
        <input type="text" name="password" value="">
        <button type="submit" name="button">Singup</button>
    </form>
{% endblock %}